Make updates to functions to accommodate both pediatrics and adults notebooks
mitre/GrowthViz pull request #17
Opened 2021-04-22 15:37 UTC by andersonmeredithk

2021-04-22 17:34 UTC, dchud commented on GrowthViz-adults.py
> +charts.overlap_view_adults(obs_df=obs_wbmi, subjid=val, param='WEIGHTKG', include_carry_forward=True,
Good to use `subjid` here instead of `id`, which is another python built-in!

2021-04-22 22:45 UTC, dchud requested changes
Minor details noted in prior comments.

2021-04-23 15:01 UTC, andersonmeredithk commented on sumstats.py
> +  dta_forz = dta_forz_long.pivot_table(index=['Sex', 'age'], columns='param2', values=['Mean', 'sd'], aggfunc='first') #.reset_index()
The capitalization is to make adults variable names consistent with pediatrics percentiles data so certain functions work for both notebooks - is that a reasonable approach?

2021-04-23 15:02 UTC, andersonmeredithk commented on charts.py
> +  Creates a chart showing the trajectory for an individual with all values present. All values will
I am not following a particular style guide, although I can if you direct me to one you recommend. I added a separate ticket for this, thanks.

2021-04-23 15:42 UTC, dchud commented on sumstats.py
> +  dta_forz = dta_forz_long.pivot_table(index=['Sex', 'age'], columns='param2', values=['Mean', 'sd'], aggfunc='first') #.reset_index()
It is reasonable! Perhaps just add a comment right above it that says something to that effect?

2021-04-23 21:19 UTC, dchud commented on charts.py
> +  Creates a chart showing the trajectory for an individual with all values present. All values will
Great! I added a comment with some suggestions over on #18.

No need to do it all now for this PR!

2021-04-23 21:22 UTC, dchud commented on processdata.py
> +  return df
Just a minor change here, I would follow the advice at https://stackoverflow.com/a/256260 with something like:

```python
else:
  raise ValueError("Mode must 'adults' or 'pediatrics'")
```

Just to be super-explicit that this is an error. `ValueError` is a built-in Exception.

2021-04-23 21:23 UTC, dchud requested changes
Just the one `ValueError` recommendation.

2021-04-23 21:27 UTC, dchud commented on processdata.py
> +# figure out issue with duplicated header row
Looks like you addressed this in the CSV file? Resolving, thinking "yes".

2021-04-26 16:46 UTC, merged